apiVersion: apps/v1
kind: Deployment
metadata:
  name: decode
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: modelserver
          command: ["vllm", "serve"]
          args:
            - "openai/gpt-oss-120b"
            - "--max-model-len=4096"
            - "--enable-chunked-prefill"
            - "--tensor-parallel-size=1"
            - "--gpu-memory-utilization=0.90"
            - "--max-num-seqs=1024"
            - "--quantization=fp4"
            - "--disable-access-log-for-endpoints=/health,/metrics,/v1/models"
          env:
            - name: HUGGING_FACE_HUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: llm-d-hf-token
                  key: HF_TOKEN
          resources:
            limits:
              cpu: "16"
              memory: 160Gi
              nvidia.com/gpu: 1
            requests:
              cpu: "4"
              memory: 80Gi
              nvidia.com/gpu: 1
          volumeMounts:
            - mountPath: /dev/shm
              name: shm
          startupProbe:
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 120
          livenessProbe:
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
      volumes:
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: 32Gi
